name = "glistix_birl"
version = "1.6.1"
description = "Glistix fork of birl, a Date / Time handling library"
gleam = ">= 0.32.0"
internal_modules = ["birl/zones"]
licences = ["Apache-2.0"]
repository = { type = "github", user = "glistix", repo = "birl" }
links = [{ title = "Gleam", href = "https://gleam.run" }]

[dependencies]
ranger = ">= 1.2.0 and < 1.4.0"
gleam_stdlib = ">= 0.36.0 and < 0.38.0"

[dev-dependencies]
glistix_gleeunit = ">= 1.0.0 and < 2.0.0"

# Locally, patch gleam_stdlib to glistix_stdlib
[glistix.preview.patch]
gleam_stdlib = { name = "glistix_stdlib", version = ">= 0.36.0 and < 0.38.0" }
