name = "birl"
version = "1.7.0"
description = "Glistix fork of birl, a Date / Time handling library"
gleam = ">= 0.32.0"
internal_modules = ["birl/zones"]
licences = ["Apache-2.0"]
repository = { type = "github", user = "glistix", repo = "birl" }
links = [{ title = "Gleam", href = "https://gleam.run" }]

[dependencies]
ranger = "~> 1.2"
# Run 'git submodule add --name stdlib -- https://github.com/glistix/stdlib external/stdlib'
# to clone Glistix's stdlib patch to the local path specified below. This is needed so stdlib
# will work on the Nix target. Hex dependents will use the stdlib version specified below,
# in [glistix.preview.hex-patch], instead.
gleam_stdlib = { path = "./external/stdlib" }

[dev-dependencies]
glistix_gleeunit = ">= 1.0.0 and < 2.0.0"
